name: Make test data

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - # Run every day at 2:00 UTC
    - cron: "0 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/AstarVienna/ScopeSim_Data.git
          pip install git+https://github.com/AstarVienna/ScopeSim.git
          pip install astar-utils numpy more-itertools astropy PyYAML scopesim_templates
      - name: Run recipes
        run: |
          python ESO/downloadPackages.py
          python ESO/run_recipes.py --small --doCalib=1 --sequence=1 --doStatic --small --outputDir metis_sim_small_1/data
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Update test data"
          branch: update-test-data
          delete-branch: true
          title: "[Assist PR] Update test data"
          body: |
            Update test data.
            Auto-generated.
          labels: |
            automated
          draft: false
